version: '3.9'
services:
  backend:
    container_name: compose-back-container
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: compose-back-optimal-image
    networks:
      - backend
    ports: 
      - 4000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure

  frontend:
    container_name: compose-front-container
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: compose-front-optimal-image
    networks:
      - frontend
    ports: 
      - 8081:80
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres 
    networks:
      - backend
    volumes: 
      - postgres_data:/data/postgres
    env_file:
      - .env
    restart: on-failure

  adminer:
    networks:
      - backend
    container_name: adminer
    image: adminer 
    ports:
      - 3005:8080
    depends_on:
      - postgres
    restart: on-failure

networks:
  frontend:
  backend:

volumes:
  postgres_data: